Add colossalai examples
t9k/examples pull request #7
Opened 2023-03-02 08:56 UTC by xyxxxxx

2023-03-02 09:52 UTC, ppkube requested changes

2023-03-02 09:52 UTC, ppkube commented on colossalai/opt/job.yaml
> +    image: tsz.io/t9k/colossalai:0.2.5-opt
use a public  (docker hub) registry

2023-03-02 09:52 UTC, ppkube commented on colossalai/opt/job.yaml
> +        #     volumeMounts:
pleas explain in README how this `data` volume can be used.  There is a separate process to download data and store them in  pvc `facebook-opt-30b`?

2023-03-02 09:52 UTC, ppkube commented on colossalai/README.md
> +    **适当的设置**指队列的优先级、是否可被抢占以及节点筛选的设置。节点筛选一般应添加适当的标签匹配规则，以限制队列可以使用的节点，例如可以匹配 `sched.tensorstack.dev/accelerator: nvidia-gpu`、`sched.tensorstack.dev/node-alloc-mode: nvidia`、`nvidia.com/gpu.product: NV
改为：

 **适当的设置**指队列优先级、是否可被抢占以及、通过节点筛选机制选择的 GPU 型号等。

2023-03-03 11:27 UTC, xyxxxxx commented on colossalai/opt/job.yaml
> +    image: tsz.io/t9k/colossalai:0.2.5-opt
fixed

2023-03-03 11:29 UTC, xyxxxxx commented on colossalai/opt/job.yaml
> +        #     volumeMounts:
使用了新的方案，现在模型检查点会由其中一个工作器下载到 PVC `colossalai` 中

2023-03-03 15:46 UTC, ppkube approved these changes
lgtm

2023-03-03 15:46 UTC, merged